apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name}}-config
  labels:
    name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  .env: |-
    APP_ENV='%env(string:APP_ENV)%'
    APP_SECRET='%env(string:APP_SECRET)%'
    DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_DATABASE}?serverVersion=8.0&charset=utf8mb4




