{{- $valuesRoot:= dict "valuesRoot" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}

spec:
  replicas: {{ .Values.deployment.minimumReplicaCount }}
  strategy:
    type: {{ .Values.deployment.deploymentStrategy }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.maxSurge }}
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
  selector:
    matchLabels:
        app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry}}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- include "env.vars" $valuesRoot | indent 10 }}
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
                memory: {{ .Values.container.memory.request }}
                cpu: {{ .Values.container.cpu.request }}
            limits:
                memory: {{ .Values.container.memory.limit }}
                cpu: {{ .Values.container.cpu.limit }}


