name: Linting and Testing

on: [push,pull_request]

jobs:
  code_check:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, sml, ctype, json
          tools: composer

      - name: Install depencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Code Sniffing PSR12
        run: |
          vendor/bin/phpcs --standard=ruleset.xml --extensions=php --tab-width=4 -sp src tests










